name: Dump Variables

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types:
      - dumpvars
jobs:
  dump_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1

      - name: Configure Git
        id: git
        run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
        shell: bash

      - name: Dump Job Context
        run: |
          echo "Job Context:"
          echo '${{ toJson(job) }}' | jq '.'

      - name: Dump Step Context
        run: |
          echo "Step Context:"
          echo '${{ toJson(steps) }}' | jq '.'

      - name: Dump Workflow Context
        run: |
          echo "Workflow Context:"
          echo '${{ toJson(env) }}' | jq '.'

      - name: Dump GitHub Context
        run: |
          echo "GitHub Context:"
          echo '${{ toJson(github) }}' | jq '.'

      - name: Swagger
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          npm install -g openapi-to-md
          docker run --name swagger -p 8080:8080 --rm -d quay.io/ortelius/ms-dep-pkg-r:main-v10.0.705-g5a746f
          sleep 5
          wget http://localhost:8080/openapi.json -O /tmp/openapi.json
          docker stop swagger
          sed -i.bak "/\[Discord\]/q" README.md && openapi-to-md /tmp/openapi.json >> README.md && rm README.md.bak
          git pull
          git add docs
          git commit -m "update openapi docs"
          git push
