name: Dump Variables

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types:
      - dumpvars
jobs:
  dump_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Dump Job Context
        run: |
          echo "Job Context:"
          echo '${{ toJson(job) }}' | jq '.'

      - name: Dump Step Context
        run: |
          echo "Step Context:"
          echo '${{ toJson(steps) }}' | jq '.'

      - name: Dump Workflow Context
        run: |
          echo "Workflow Context:"
          echo '${{ toJson(env) }}' | jq '.'

      - name: Dump GitHub Context
        run: |
          echo "GitHub Context:"
          echo '${{ toJson(github) }}' | jq '.'
