name: Dump Variables

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types:
      - dumpvars
jobs:
  dump_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: execute py script
        run: |
          python main.py --loaddata
          find . -name mitre.joblib -print

      - name: Build and Push Docker Image
        id: build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          push: false
          tags: ms:latest
          platforms: linux/amd64
          attests: type=provenance,type=sbom
        timeout-minutes: 100
