name: Dump Variables

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types:
      - dumpvars
jobs:
  dump_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Dump Job Context
        run: |
          echo "Job Context:"
          echo '${{ toJson(job) }}' | jq '.'

      - name: Dump Step Context
        run: |
          echo "Step Context:"
          echo '${{ toJson(steps) }}' | jq '.'

      - name: Dump Workflow Context
        run: |
          echo "Workflow Context:"
          echo '${{ toJson(env) }}' | jq '.'

      - name: Dump GitHub Context
        run: |
          echo "GitHub Context:"
          echo '${{ toJson(github) }}' | jq '.'

      - name: Swagger
        run: |
          docker run --name swagger -p 8080:8080 --rm -d quay.io/ortelius/ms-dep-pkg-r:main-v10.0.705-g5a746f
          mkdir docs 2>/dev/null | test 1
          sleep 10
          wget http://localhost:8080/openapi.json -o docs/openapi.json
          ls docs
          docker stop swagger
          npm install -g widdershins
          cd docs
          widdershins openapi.json -o openapi.md
          cd ..
          git add docs
          git commit -m "update openapi docs"
          git push
